### ISSUE TITLE
Doesn't work with celery version 3.0

### ISSUE THREAD

**Issue by brockhaywood** [winhamwr/mixpanel-celery#7]
Version 3 of celery has broken compatbility with this library. The logger no longer seems to be available:

Traceback (most recent call last):
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/celery/task/trace.py", line 403, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/Users/sendhub-dev/dev/sendhub/project/app/api/v1/events.py", line 38, in mixPanelListener
    tracker.run(name, properties, token=settings.MIXPANEL_API_KEY)
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/mixpanel/tasks.py", line 42, in run
    if l.logger.getEffectiveLevel() == logging.DEBUG:
AttributeError: 'ProcessAwareLogger' object has no attribute 'logger'
